# Generated by Django 5.2.8 on 2025-11-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Ảnh banner')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='Link đến')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('status', models.CharField(choices=[('NEW', 'Mới'), ('READ', 'Đã đọc'), ('REPLIED', 'Đã trả lời')], default='NEW', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên tổ')),
                ('leader_name', models.CharField(blank=True, max_length=100, verbose_name='Tổ trưởng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Tổ chuyên môn',
                'verbose_name_plural': 'Tổ chuyên môn',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Số hiệu văn bản')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('doc_type', models.CharField(choices=[('CONG_VAN', 'Công văn'), ('QUYET_DINH', 'Quyết định'), ('TKB', 'Thời khóa biểu'), ('BIEU_MAU', 'Biểu mẫu')], max_length=50, verbose_name='Loại văn bản')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File đính kèm')),
                ('file_size', models.IntegerField(default=0, verbose_name='Kích thước (KB)')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Ngày ban hành')),
                ('signer', models.CharField(blank=True, max_length=100, verbose_name='Người ký')),
                ('download_count', models.IntegerField(default=0, verbose_name='Lượt tải')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Văn bản',
                'verbose_name_plural': 'Văn bản',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('url', models.URLField(max_length=500, verbose_name='Đường dẫn')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Icon')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Liên kết ngoài',
                'verbose_name_plural': 'Liên kết ngoài',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trang tĩnh',
                'verbose_name_plural': 'Trang tĩnh',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên album')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album ảnh',
                'verbose_name_plural': 'Album ảnh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('video_url', models.URLField(max_length=500, verbose_name='Link video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Ảnh đại diện')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Video nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Chú thích')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.photoalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Ảnh',
                'verbose_name_plural': 'Ảnh',
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Ảnh đại diện')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Ảnh đại diện')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('bio', models.TextField(blank=True, verbose_name='Tiểu sử')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.department', verbose_name='Tổ chuyên môn')),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Nhân sự',
                'ordering': ['sort_order', 'full_name'],
            },
        ),
    ]
