# Generated by Django 5.2.9 on 2026-01-01 05:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_slug_alter_page_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Văn bản', 'verbose_name_plural': 'Công văn - Văn bản'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Ảnh bìa'),
        ),
    ]
