# Generated by Django 5.2.9 on 2026-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_cloudinary_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='core_docume_publish_96cd38_idx',
            old_name='core_docume_publishe_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='core_docume_doc_typ_a55021_idx',
            old_name='core_docume_doc_typ_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số hiệu văn bản'),
        ),
        migrations.AlterField(
            model_name='document',
            name='download_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Lượt tải'),
        ),
        migrations.AlterField(
            model_name='document',
            name='signer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người ký'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tiêu đề'),
        ),
    ]
