# Generated by Django 5.2.9 on 2026-01-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_docume_publishe_idx_core_docume_publish_96cd38_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc'),
        ),
    ]
