# Generated by Django 5.2.10 on 2026-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_source',
            field=models.CharField(blank=True, choices=[('SO_GDDT', 'Sở GD&ĐT'), ('TRUONG', 'Trường'), ('HDND_UBND', 'HĐND-UBND xã'), ('THONG_BAO', 'Thông báo')], max_length=50, null=True),
        ),
    ]
