# Generated by Django 5.2.9 on 2026-02-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp')),
                ('grade', models.IntegerField(choices=[(10, 'Khối 10'), (11, 'Khối 11'), (12, 'Khối 12')], verbose_name='Khối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên (VD: HK1 2025-2026)')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Năm học',
                'verbose_name_plural': 'Năm học',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='doc_source',
            field=models.CharField(blank=True, choices=[('SO_GDDT', 'Sở GD&ĐT'), ('TRUONG', 'Trường'), ('HDND_UBND', 'HĐND-UBND xã'), ('THONG_BAO', 'Thông báo')], max_length=50, null=True, verbose_name='Phát hành'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Chủ nhật')], verbose_name='Thứ')),
                ('period', models.IntegerField(verbose_name='Tiết (1-10)')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Môn học')),
                ('teacher_name', models.CharField(blank=True, max_length=100, verbose_name='Giáo viên')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng học')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.schoolclass', verbose_name='Lớp')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='core.schoolyear', verbose_name='Học kỳ/Năm học')),
            ],
            options={
                'verbose_name': 'Chi tiết TKB',
                'verbose_name_plural': 'Chi tiết TKB',
                'ordering': ['school_year', 'school_class', 'day_of_week', 'period'],
                'unique_together': {('school_year', 'school_class', 'day_of_week', 'period')},
            },
        ),
    ]
