# Generated by Django 5.2.10 on 2026-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_original_filename'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle the case where the column
        # already exists in the DB (e.g. created by a previous deployment).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "core_document" ADD COLUMN IF NOT EXISTS "doc_source" varchar(50) NULL',
                    reverse_sql='ALTER TABLE "core_document" DROP COLUMN IF EXISTS "doc_source"',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='document',
                    name='doc_source',
                    field=models.CharField(blank=True, choices=[('SO_GDDT', 'Sở GD&ĐT'), ('TRUONG', 'Trường'), ('HDND_UBND', 'HĐND-UBND xã'), ('THONG_BAO', 'Thông báo')], max_length=50, null=True),
                ),
            ],
        ),
    ]
