# Generated by Django 5.2.11 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document_doc_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_source',
            field=models.CharField(blank=True, choices=[('SO_GDDT', 'Sở GD&ĐT'), ('TRUONG', 'Trường'), ('HDND_UBND', 'HĐND-UBND xã'), ('THONG_BAO', 'Thông báo')], max_length=50, null=True, verbose_name='Phát hành'),
        ),
    ]
