# Generated by Django 5.2.11 on 2026-02-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schoolclass_schoolyear_document_doc_source_and_more'),
        ('core', '0008_alter_document_doc_source'),
    ]

    operations = [
    ]
