# Generated by Django 5.2.11 on 2026-03-15

from urllib.parse import parse_qs, urlparse

from django.db import migrations, models


VALID_SOURCES = {"SO_GDDT", "TRUONG", "HDND_UBND", "THONG_BAO"}


def migrate_sidebar_document_sources(apps, schema_editor):
    SidebarDocumentItem = apps.get_model("core", "SidebarDocumentItem")

    for item in SidebarDocumentItem.objects.all():
        href = getattr(item, "href", "") or ""
        source = parse_qs(urlparse(href).query).get("source", [None])[0]

        if source in VALID_SOURCES:
            item.document_source = source
            item.save(update_fields=["document_source"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sidebardocumentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebardocumentitem",
            name="document_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SO_GDDT", "Sở GD&ĐT"),
                    ("TRUONG", "Trường"),
                    ("HDND_UBND", "HĐND-UBND xã"),
                    ("THONG_BAO", "Thông báo"),
                ],
                max_length=50,
                null=True,
                verbose_name="Document source",
            ),
        ),
        migrations.RunPython(migrate_sidebar_document_sources, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sidebardocumentitem",
            name="href",
        ),
    ]

