# Generated by Django 5.2.11 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sidebar_document_item_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="SidebarNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                ("href", models.CharField(max_length=500, verbose_name="Href")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sort order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "site_setting",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="news_items",
                        to="core.sitesetting",
                        verbose_name="Site setting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sidebar news item",
                "verbose_name_plural": "Sidebar news items",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]

