# Generated by Django 5.2.11 on 2026-03-18

from urllib.parse import urlparse

from django.db import migrations, models


def migrate_news_href_to_tab(apps, schema_editor):
    SidebarNewsItem = apps.get_model("core", "SidebarNewsItem")

    for item in SidebarNewsItem.objects.all():
        href = (getattr(item, "href", "") or "").lower()
        path = urlparse(href).path

        if "thoi-khoa-bieu" in path:
            item.news_tab = "THOI_KHOA_BIEU"
        elif "thi-kiem-tra" in path:
            item.news_tab = "THI_KIEM_TRA"
        else:
            item.news_tab = "THOI_KHOA_BIEU"

        item.save(update_fields=["news_tab"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_sidebarnewsitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebarnewsitem",
            name="news_tab",
            field=models.CharField(
                choices=[
                    ("THOI_KHOA_BIEU", "Thời khóa biểu"),
                    ("THI_KIEM_TRA", "Thi - Kiểm tra"),
                ],
                default="THOI_KHOA_BIEU",
                max_length=50,
                verbose_name="News tab",
            ),
        ),
        migrations.RunPython(migrate_news_href_to_tab, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sidebarnewsitem",
            name="href",
        ),
        migrations.RemoveField(
            model_name="sidebarnewsitem",
            name="label",
        ),
    ]

