# Generated by Django 5.2.11 on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


def migrate_news_tab_to_category(apps, schema_editor):
    SidebarNewsItem = apps.get_model("core", "SidebarNewsItem")
    Category = apps.get_model("core", "Category")

    slug_by_tab = {
        "THOI_KHOA_BIEU": "thoi-khoa-bieu",
        "THI_KIEM_TRA": "thi-kiem-tra",
    }

    for item in SidebarNewsItem.objects.all():
        slug = slug_by_tab.get(getattr(item, "news_tab", ""))
        category = Category.objects.filter(slug=slug).first() if slug else None
        item.category = category
        item.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sidebar_news_item_tab"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebarnewsitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sidebar_news_items",
                to="core.category",
                verbose_name="Category",
            ),
        ),
        migrations.RunPython(migrate_news_tab_to_category, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sidebarnewsitem",
            name="news_tab",
        ),
    ]

