# Generated by Django 5.2.11 on 2026-03-21

from django.db import migrations, models


def seed_staff_groups(apps, schema_editor):
    StaffGroup = apps.get_model("core", "StaffGroup")

    defaults = [
        ("Ban Giám hiệu", "ban-giam-hieu", 1),
        ("Chi bộ Đảng", "chi-bo-dang", 2),
        ("Đoàn Thanh niên", "doan-thanh-nien", 3),
        ("Tổ Văn phòng", "to-van-phong", 4),
        ("Tổ Chuyên môn", "to-chuyen-mon", 5),
        ("Hội cha mẹ học sinh", "hoi-cha-me-hoc-sinh", 6),
    ]

    for name, slug, sort_order in defaults:
        StaffGroup.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_sidebar_news_item_category_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên nhóm")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True, verbose_name="Slug")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                ("is_active", models.BooleanField(default=True, verbose_name="Hiển thị")),
            ],
            options={
                "verbose_name": "Nhóm nhân sự",
                "verbose_name_plural": "Nhóm nhân sự",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="sidebar_groups",
            field=models.ManyToManyField(blank=True, related_name="staff_members", to="core.staffgroup", verbose_name="Nhóm sidebar"),
        ),
        migrations.RunPython(seed_staff_groups, migrations.RunPython.noop),
    ]

