# Generated by Django 5.2.11 on 2026-03-21

from django.db import migrations, models


def migrate_groups_to_staff_flags(apps, schema_editor):
    Staff = apps.get_model("core", "Staff")

    flag_map = {
        "ban-giam-hieu": "is_ban_giam_hieu",
        "chi-bo-dang": "is_chi_bo_dang",
        "doan-thanh-nien": "is_doan_thanh_nien",
        "to-van-phong": "is_to_van_phong",
        "to-chuyen-mon": "is_to_chuyen_mon",
        "hoi-cha-me-hoc-sinh": "is_hoi_cha_me_hoc_sinh",
    }

    for staff in Staff.objects.all():
        update_fields = []
        for group in staff.sidebar_groups.all():
            field_name = flag_map.get(group.slug)
            if field_name and not getattr(staff, field_name):
                setattr(staff, field_name, True)
                update_fields.append(field_name)

        if update_fields:
            staff.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_staffgroup_and_staff_sidebar_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_ban_giam_hieu",
            field=models.BooleanField(default=False, verbose_name="Ban giám hiệu"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_chi_bo_dang",
            field=models.BooleanField(default=False, verbose_name="Chi bộ Đảng"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_doan_thanh_nien",
            field=models.BooleanField(default=False, verbose_name="Đoàn Thanh niên"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_hoi_cha_me_hoc_sinh",
            field=models.BooleanField(default=False, verbose_name="Hội cha mẹ học sinh"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_to_chuyen_mon",
            field=models.BooleanField(default=False, verbose_name="Tổ Chuyên môn"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_to_van_phong",
            field=models.BooleanField(default=False, verbose_name="Tổ Văn phòng"),
        ),
        migrations.RunPython(migrate_groups_to_staff_flags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="staff",
            name="sidebar_groups",
        ),
        migrations.DeleteModel(
            name="StaffGroup",
        ),
    ]

