# Generated by Django 5.2.11 on 2026-03-21

from django.db import migrations, models


def migrate_flags_to_tags(apps, schema_editor):
    Staff = apps.get_model("core", "Staff")
    StaffFilterTag = apps.get_model("core", "StaffFilterTag")

    tag_defs = [
        ("ban-giam-hieu", "Ban giám hiệu", "is_ban_giam_hieu", 1),
        ("chi-bo-dang", "Chi bộ Đảng", "is_chi_bo_dang", 2),
        ("doan-thanh-nien", "Đoàn Thanh niên", "is_doan_thanh_nien", 3),
        ("to-van-phong", "Tổ Văn phòng", "is_to_van_phong", 4),
        ("to-chuyen-mon", "Tổ Chuyên môn", "is_to_chuyen_mon", 5),
        ("hoi-cha-me-hoc-sinh", "Hội cha mẹ học sinh", "is_hoi_cha_me_hoc_sinh", 6),
    ]

    tags = {}
    for slug, name, _, sort_order in tag_defs:
        tag, _ = StaffFilterTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )
        tags[slug] = tag

    for staff in Staff.objects.all():
        for slug, _, flag_field, _ in tag_defs:
            if getattr(staff, flag_field, False):
                staff.filter_tags.add(tags[slug])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_staff_flags_replace_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffFilterTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tên bộ lọc")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True, verbose_name="Slug")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                ("is_active", models.BooleanField(default=True, verbose_name="Hiển thị")),
            ],
            options={
                "verbose_name": "Tag lọc nhân sự",
                "verbose_name_plural": "Tag lọc nhân sự",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="filter_tags",
            field=models.ManyToManyField(blank=True, related_name="staff_members", to="core.stafffiltertag", verbose_name="Tag lọc sidebar"),
        ),
        migrations.RunPython(migrate_flags_to_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="staff",
            name="is_ban_giam_hieu",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_chi_bo_dang",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_doan_thanh_nien",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_hoi_cha_me_hoc_sinh",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_to_chuyen_mon",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="is_to_van_phong",
        ),
    ]

