# Generated by Django 5.2.11 on 2026-03-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesetting_quote_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafffiltertag',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Chức danh hiển thị', 'verbose_name_plural': 'Quản lý chức danh'},
        ),
        migrations.AlterField(
            model_name='sidebarintroitem',
            name='link_type',
            field=models.CharField(choices=[('STAFF_ALL', 'Danh sach nhan su'), ('STAFF_FILTER', 'Nhan su theo chuc danh'), ('CUSTOM', 'Duong dan tuy chinh')], default='STAFF_FILTER', max_length=20, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='core.stafffiltertag', verbose_name='Chức danh hiển thị'),
        ),
        migrations.AlterField(
            model_name='stafffiltertag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
