# Generated by Django 5.2.12 on 2026-06-22 16:51

import cloudinary.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_banner_cropping"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", cloudinary.models.CloudinaryField(max_length=255, resource_type="raw", validators=[core.validators.DocumentFileValidator()], verbose_name="File dinh kem")),
                ("file_size", models.IntegerField(default=0, editable=False, verbose_name="Kich thuoc (KB)")),
                ("original_filename", models.CharField(blank=True, max_length=255, verbose_name="Ten file goc")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Thu tu")),
                ("download_count", models.IntegerField(default=0, editable=False, verbose_name="Luot tai")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="core.post", verbose_name="Bai viet")),
            ],
            options={
                "verbose_name": "File dinh kem bai viet",
                "verbose_name_plural": "File dinh kem bai viet",
                "ordering": ["sort_order", "id"],
                "indexes": [models.Index(fields=["post", "sort_order"], name="core_postat_post_id_02453a_idx")],
            },
        ),
    ]
